name: PHP CI/CD with AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'  # Replace with the desired PHP version

      - name: Install dependencies
        run: composer install

      - name: Build project (if applicable)
        # Add any build commands if needed, like compiling assets

      - name: Deploy to AWS EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}  # Add your EC2 server's public IP/domain
          username: ${{ secrets.AWS_EC2_USERNAME }}  # Add the SSH username for your EC2 instance
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}  # Add your SSH private key as a secret
          source: '.'  # Source directory of your project to be copied to the server
          target: '/var/www/html/'  # Target directory on the server where the project will be deployed

      - name: Install dependencies on EC2
        run: ssh ${{ secrets.AWS_EC2_USERNAME }}@${{ secrets.AWS_EC2_HOST }} 'cd /var/www/html/ && composer install --no-dev'

      - name: Restart Apache (or your web server)
        run: ssh ${{ secrets.AWS_EC2_USERNAME }}@${{ secrets.AWS_EC2_HOST }} 'sudo service apache2 restart'
        # If you're using a different web server like Nginx, adjust the command accordingly

      - name: Test Deployment (optional)
        # Add any post-deployment tests or checks to ensure the deployment was successful
